- op: replace
  path: /data/VERSION
  value: "26.2"
- op: replace
  path: /data/TYPE
  value: "PAPER"
- op: add
  path: /data/GEYSER_AUTH_TYPE
  value: "floodgate"
- op: add
  path: /data/ICON
  value: "https://i.pinimg.com/736x/19/3b/b1/193bb161d0f6e2d501aa50493232259f.jpg"
- op: add
  path: /data/MOTD
  value: "Compà chi minchia ci talìi"
- op: add
  path: /data/OVERRIDE_ICON
  value: "true"
- op: add
  path: /data/PLUGINS
  value: |-
    https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
    https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot