apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft-picciotti

resources:
  - ../../../Base/Minecraft/

patches:
- path: statefulSetPatch.yaml
  target:
    kind: StatefulSet
    name: minecraft-server

- path: configMapPatch.yaml
  target:
    kind: ConfigMap
    name: minecraft-config

- path: servicesPatch.yaml
  target:
    kind: Service
    name: minecraft-server