apiVersion: v1
kind: ConfigMap
metadata:
  name: scp-config
  namespace: scp-server
data:
  config_remoteadmin.txt: |
    #Let's assign roles (you can modify them and create custom roles below)
    #UserID format is SteamId64Here@steam, DiscordUserIDHere@discord, etc...
    Members:
     - 76561198198669835@steam: owner
     - 76561197970106562@steam: admin
     - 76561198099259861@steam: admin

    #Should Secret Lab development staff be able to use the Remote Admin?
    enable_staff_access: false

    #Should Secret Lab CEO and managers be able to use Remote Admin? (We do not abuse our powers) 
    enable_manager_access: true

    #Allow remote admin access for the banning team, to allow them searching and fighting cheaters globally
    enable_banteam_access: true

    #Enable reserved slots for the banning team (they are restricted by reserved slots limit set in the gameplay config)
    enable_banteam_reserved_slots: true

    #Allow the banning team to bypass georestrictions on the server
    enable_banteam_bypass_geoblocking: true

    #Let's define roles
    owner_badge: SERVER OWNER
    owner_color: red
    owner_cover: true
    owner_hidden: false
    owner_kick_power: 255
    owner_required_kick_power: 255

    admin_badge: ADMIN
    admin_color: red
    admin_cover: true
    admin_hidden: false
    admin_kick_power: 1
    admin_required_kick_power: 2

    moderator_badge: MODERATOR
    moderator_color: silver
    moderator_cover: true
    moderator_hidden: false
    moderator_kick_power: 0
    moderator_required_kick_power: 1

    Roles:
     - owner
     - admin
     - moderator

    Permissions:
     - KickingAndShortTermBanning: [owner, admin, moderator]
     - BanningUpToDay: [owner, admin, moderator]
     - LongTermBanning: [owner, admin]
     - ForceclassSelf: [owner, admin, moderator]
     - ForceclassToSpectator: [owner, admin, moderator]
     - ForceclassWithoutRestrictions: [owner, admin]
     - GivingItems: [owner, admin]
     - WarheadEvents: [owner, admin, moderator]
     - RespawnEvents: [owner, admin]
     - RoundEvents: [owner, admin, moderator]
     - SetGroup: [owner]
     - GameplayData: [owner, admin]
     - Overwatch: [owner, admin, moderator]
     - FacilityManagement: [owner, admin, moderator]
     - PlayersManagement: [owner, admin]
     - PermissionsManagement: [owner]
     - ServerConsoleCommands: []
     - ViewHiddenBadges: [owner, admin, moderator]
     - ServerConfigs: [owner]
     - Broadcasting: [owner, admin, moderator]
     - PlayerSensitiveDataAccess: [owner, admin, moderator]
     - Noclip: [owner, admin]
     - AFKImmunity: [owner, admin]
     - AdminChat: [owner, admin, moderator]
     - ViewHiddenGlobalBadges: [owner, admin, moderator]
     - Announcer: [owner, admin]
     - Effects: [owner, admin]
     - FriendlyFireDetectorImmunity: [owner, admin, moderator]
     - FriendlyFireDetectorTempDisable: [owner, admin]
     - ServerLogLiveFeed: [owner, admin]
     - ExecuteAs: [owner]
     - Vanish: [owner]

    override_password: none
    override_password_role: owner
    allow_central_server_commands_as_ServerConsoleCommands: false
    enable_predefined_ban_templates: true
    PredefinedBanTemplates:
     - [0, Consider this a warning!]
     - [3600, Mic Spamming]
     - [86400, Team Killing (Minor Offence)]
     - [604800, Team Killing (Major Offence)]
     - [1577000000, Abusing Exploits]

  config_gameplay.txt: |
    #Server main settings
    server_name: SCP Server on Kubernetes
    player_list_title: default
    player_list_title_rate: default
    serverinfo_pastebin_id: 7wV681fT
    server_ip: auto
    max_players: 20
    server_tickrate: 60
    use_reserved_slots: true
    lobby_waiting_time: default
    use_native_sockets: true
    ipv4_bind_ip: 0.0.0.0
    ipv6_bind_ip: ::
    contact_email: default
    
    #Spawn settings
    use_crypto_rng: false
    team_respawn_queue: default
    late_join_time: 0
    
    ## Player Info Range ##
    # This controls the default range that the player information text appears on clients.
    # Default is 10.
    player_info_range: 10
    
    ## Stamina system settings ##
    
    # The percentage of stamina used per second while sprinting.
    # 0.05 = 5%, 0.33 = 33%, etc.
    # NOTE: Stamina is currently only utilized on humans.
    # 0 to disable, but this *will* cause weirdness with status effects
    # and other mechanics, so we recommend keeping it on!
    stamina_balance_use: 0.05
    
    # The time (in seconds) that newly-spawned players can sprint
    # without consuming stamina. Used to reduce visual artifacts.
    # We recommend to put it at least 2 seconds
    stamina_balance_immunity: 3
    
    # The seconds that must pass before stamina starts regenerating after
    #INVALID - the player stops sprinting.
    # Lower values are more liekly to be exploited by players
    # Higher higher can be annoying to players.
    stamina_balance_regen_cd: 1
    
    # How fast the stamina regenerates.
    # This is a multiplier for the default setting,
    # which is based on a curve - not a specific value.
    stamina_balance_regen_speed: 1
    
    #Random-stuff settings (-1: random)
    server_forced_class: -1
    map_seed: -1
    
    #Misc gameplay settings
    intercom_cooldown: 120
    intercom_max_speech_time: 20
    auto_round_restart_time: 10
    friendly_fire: false
    friendly_fire_multiplier: 0.4
    warhead_tminus_start_duration: 90
    lock_gates_on_countdown: true
    isolate_zones_on_countdown: false
    open_doors_on_countdown: true
    keep_items_after_escaping: true
    disable_decontamination: false
    allow_disarmed_interaction: false
    914_mode: default
    sinkhole_slow_amount: 30
    sinkhole_spawn_chance: 0
    disconnect_drop: true
    end_round_on_one_player: false
    cuffed_escapee_change_team: true
    pd_exit_count: 2
    
    #How many seconds someone is AFK sitting in their spawn location before they are kicked. Set to 0 or lower to disable. (Due to the 079 intro screen 079 has 13 extra seconds to be AFK.)
    afk_time: 90
    constantly_check_afk: false
    afk_kick_message: AFK
    
    #Spawn Protect settings
    spawn_protect_enabled: default
    spawn_protect_time: default
    spawn_protect_can_shoot: default
    spawn_protect_prevent_all: default
    spawn_protect_team: [1, 2]
    
    #Auto Event settings
    auto_warhead_start_minutes: 0
    auto_warhead_lock: true
    auto_warhead_broadcast_enabled: true
    auto_warhead_broadcast_message: Alpha Warhead is being automatically detonated and cannot be cancelled.
    auto_warhead_broadcast_time: 10
    auto_warhead_detonate_broadcast: Automatic Alpha Warhead has been detonated.
    auto_warhead_detonate_broadcast_time: 10
    auto_decon_broadcast_enabled: false
    auto_decon_broadcast_message: Light Containment Zone is now decontaminated
    auto_decon_broadcast_time: 10
    
    #Deadman's Switch settings
    dms_enabled: true
    dms_activation_time: 240
    
    #Metrics are used to anonymously track players' in-game activities and can be used to improve gameplay balance.
    #If set to 'true', the game will generate a JSON file containing collected metrics at the end of the round, which will be stored locally.
    save_metrics: true
    
    #Security & Anticheat (default settings are good enough in most cases)
    #Please type !private in your server console, if your server is verified, but you want to keep it hidden from the list. Type !public to make it public again.
    online_mode: true
    authentication_timeout: 45
    ip_banning: true
    enable_whitelist: false
    forward_ports: true
    enable_query: false
    query_port_shift: 0
    query_bind_ip1: 0.0.0.0
    query_socket_ip1_dualmode: false
    query_socket_ip1_linger: false
    query_bind_ip2: ::
    query_socket_ip2_dualmode: false
    query_socket_ip2_linger: false
    query_rx_buffer_size: 4096
    query_administrator_password: none
    query_permissions: 18446744073709551615
    query_kick_power: 255
    query_clients_limit: 10
    query_timeout_time: 10000
    query_maximum_time_difference: 120
    connections_delay_time: 5
    enable_sync_command_binding: false
    ratelimit_kick: true
    same_account_joining: false
    enable_fast_round_restart: false
    fast_round_restart_delay: 3.2
    display_preauth_logs: true
    rejection_suppression_threshold: 60
    challenge_issuance_suppression_threshold: 50
    
    #Enables challenge during preauthentication
    preauth_challenge: true
    
    #Reply - prevents from flooding server with preauth requests from spoofed IP addresses
    #MD5 or SHA1 - prevents from flooding with preauth requests from legitimate IP addresses as well. Requires additional time to join the server.
    preauth_challenge_mode: reply
    preauth_challenge_base_length: 10
    preauth_challenge_time_window: 12
    preauth_challenge_clean_period: 4
    
    #Only for MD5 and SHA1 challenges (higher value = longer time required to join the server)
    preauth_challenge_secret_length: 2
    
    #This enforces the player to be using same IP address to connect to the game and authenticate.
    #Enabling this blocks proxies. Not enforced if player joined from IPv4 and authenticated from IPv6 or viceversa.
    #Situations with combinating IPv4 and IPv6 addresses are being checked on central servers after authentication (only for servers on public list).
    enforce_same_ip: true
    no_enforcement_for_local_ip_addresses: true
    
    #Connections ratelimiting
    #Ratelimit time windows define how often user with the same IP/UserID can initialize new connection (once per X seconds).
    enable_ip_ratelimit: false
    enable_userid_ratelimit: false
    ip_ratelimit_window: 3
    userid_ratelimit_window: 5
    
    # - Item category limits -
    # Values of 0 are NOT unlimited and will prevent item pickups of that type entirely!
    # The inventory can hold a max of 8 items, so a limit of 8 is effectively unlimited.
    limit_category_grenade: default
    limit_category_keycard: default
    limit_category_medical: default
    limit_category_scpitem: default
    limit_category_firearm: default
    
    # - Ammo type limits -
    # Values from 1 to 65k.
    limit_ammo12gauge: default
    limit_ammo556x45: default
    limit_ammo44cal: default
    limit_ammo762x39: default
    limit_ammo9x19: default
    
    #Friendly fire punishment
    #Action is performed if someone either kills enough teammates OR deals enough damage to teammates.
    #Set kills or damage to 0 to disable that threshold.
    #Detectors priority: Respawn (kill), Window (kill), Life (kill), Round (kill), Respawn (damage), Window (damage), Life (damage), Round (damage)
    #Actions: kill, kick, ban, noop (no operation - do nothing, eg. to enable logging)
    #Damage dealt AFTER round end is ignored.
    
    ff_detector_global_broadcast_seconds: 5
    ff_detector_global_adminchat_seconds: 6
    
    #If enabled Class D personnel can damage or kill other Class D personnel without being punished for it
    ff_detector_classD_can_damage_classD: false
    
    #If set to "none" then the webhook for cheaters reporting will be used
    ff_detector_webhook_url: none
    
    
    #Per round
    ff_detector_round_enabled: false
    ff_detector_round_kills: 6
    ff_detector_round_damage: 500
    
    ff_detector_round_action: ban
    ff_detector_round_ban_time: 24h
    ff_detector_round_bankick_reason: You have been automatically banned for teamkilling.
    ff_detector_round_kill_reason: You have been automatically killed for teamkilling.
    
    ff_detector_round_adminchat_enable: false
    ff_detector_round_adminchat_message: %nick has been banned for teamkilling (round detector).
    
    ff_detector_round_broadcast_enable: true
    ff_detector_round_broadcast_message: %nick has been automatically banned for teamkilling.
    
    ff_detector_round_webhook_report: true
    
    
    #Per life (resets on respawn)
    ff_detector_life_enabled: false
    ff_detector_life_kills: 4
    ff_detector_life_damage: 300
    
    ff_detector_life_action: ban
    ff_detector_life_ban_time: 24h
    ff_detector_life_bankick_reason: You have been automatically banned for teamkilling.
    ff_detector_life_kill_reason: You have been automatically killed for teamkilling.
    
    ff_detector_life_adminchat_enable: false
    ff_detector_life_adminchat_message: %nick has been banned for teamkilling (life detector).
    
    ff_detector_life_broadcast_enable: true
    ff_detector_life_broadcast_message: %nick has been automatically banned for teamkilling.
    
    ff_detector_life_webhook_report: true
    
    
    #In a specified time window
    ff_detector_window_enabled: false
    ff_detector_window_seconds: 180
    ff_detector_window_kills: 3
    ff_detector_window_damage: 250
    
    ff_detector_window_action: ban
    ff_detector_window_ban_time: 16h
    ff_detector_window_bankick_reason: You have been automatically banned for teamkilling.
    ff_detector_window_kill_reason: You have been automatically killed for teamkilling.
    
    ff_detector_window_adminchat_enable: false
    ff_detector_window_adminchat_message: %nick has been banned for teamkilling (window detector).
    
    ff_detector_window_broadcast_enable: true
    ff_detector_window_broadcast_message: %nick has been automatically banned for teamkilling.
    
    ff_detector_window_webhook_report: true
    
    
    #In a specified time window AFTER RESPAWN
    ff_detector_spawn_enabled: true
    ff_detector_spawn_window_seconds: 120
    ff_detector_spawn_kills: 2
    ff_detector_spawn_damage: 180
    
    ff_detector_spawn_action: ban
    ff_detector_spawn_ban_time: 48h
    ff_detector_spawn_bankick_reason: You have been automatically banned for teamkilling.
    ff_detector_spawn_kill_reason: You have been automatically killed for teamkilling.
    
    ff_detector_spawn_adminchat_enable: false
    ff_detector_spawn_adminchat_message: %nick has been banned for teamkilling (spawn detector).
    
    ff_detector_spawn_broadcast_enable: true
    ff_detector_spawn_broadcast_message: %nick has been automatically banned for teamkilling.
    
    ff_detector_spawn_webhook_report: true
    
    
    #Kills made with explosions (eg. grenades) after DISCONNECTING from a server (eg. throwing a grenade and immediately closing the game)
    ff_detector_explosion_after_disconnecting_enabled: true
    
    ff_detector_explosion_after_disconnecting_action: ban
    ff_detector_explosion_after_disconnecting_ban_time: 48h
    ff_detector_explosion_after_disconnecting_bankick_reason: You have been automatically banned for teamkilling.
    
    ff_detector_explosion_after_disconnecting_adminchat_enable: false
    ff_detector_explosion_after_disconnecting_adminchat_message: %nick has been banned for teamkilling (explosion after disconnecting detector).
    
    ff_detector_explosion_after_disconnecting_broadcast_enable: true
    ff_detector_explosion_after_disconnecting_broadcast_message: %nick has been automatically banned for teamkilling.
    
    ff_detector_explosion_after_disconnecting_webhook_report: true
    
    
    #Enable this if and ONLY if you use plugin or modification that provides custom whitelist.
    #This is only to mark the server on the public list as using a whitelist.
    #More information can be found in the Verified Server Rules.
    #Ignore this config key if your server is not verified.
    custom_whitelist: false
    
    #Enable this if and ONLY if you use plugin or modification that restricts access to the server (other than whitelist, eg. password).
    #This is only to mark the server on the public list as using access restriction.
    #More information can be found in the Verified Server Rules.
    #Ignore this config key if your server is not verified.
    server_access_restriction: false
    
    #Enable this if and ONLY if your server is a Transparently Modded Server according to the definition that can be found in the Verified Server Rules.
    #Ignore this config key if your server is not verified.
    transparently_modded_server: false
    
    #port_queue is for NONDEDICATED SERVERS ONLY
    port_queue:
     - 7777
     - 7778
     - 7779
     - 7780
     - 7781
     - 7782
     - 7783
     - 7784
    
    #Enabling this will automatically ban IP of players on the server that receives a Global Ban by a Global Moderator. (Defaults to false)
    gban_ban_ip: default
    
    ban_nickname_maxlength: default
    ban_nickname_trimunicode: default
    
    #Nickname filtering, using regex
    nickname_filter: default
    nickname_filter_replacement: default
    
    #Administrative actions broadcast options
    broadcast_kicks: false
    broadcast_kick_text: %nick% has been kicked from this server.
    broadcast_kick_duration: 5
    broadcast_bans: true
    broadcast_ban_text: %nick% has been banned from this server.
    broadcast_ban_duration: 5
    
    #Server idle mode
    idle_mode_enabled: true
    idle_mode_time: 5000
    idle_mode_preauth_time: 30000
    idle_mode_tickrate: 1
    
    #Player report
    report_send_using_discord_webhook: false
    report_discord_webhook_url: PleaseSetWebhookUrlHere
    report_username: Cheater Report
    report_avatar_url: default
    report_color: 14423100
    report_server_name: My SCP:SL Server
    report_header: Player Report
    report_content: Player has just been reported.
    
    #Restart options
    #Requires LocalAdmin or a fully compatible tool.
    
    #You can set autorestart of the server after a specified amount of rounds (0 - disabled).
    restart_after_rounds: 0
    
    #Amount of time after client should rejoin after a full server restart.
    #Adjust depending on your server restart time.
    full_restart_rejoin_time: 25
    
    
    #Geoblocking
    #If your server is on the public list, please refer to Verified Server Rules for more details.
    #Modes: none, whitelist, blacklist
    geoblocking_mode: none
    
    #If enabled, players on the whitelist are able to ignore geoblocking.
    geoblocking_ignore_whitelisted: true
    
    #ISO country codes, eg. PL, US, DE
    geoblocking_whitelist:
     - AA
     - AB
     - AC
    
    geoblocking_blacklist:
     - AA
     - AB
     - AC