apiVersion: v1
kind: Service
metadata:
  name: scp-server
  namespace: scp-server
spec:
  ports:
  - name: udp
    protocol: UDP
    port: 7777
    targetPort: 7777
    nodePort: 30777
  selector:
    app: scp-server
  type: NodePort