apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scp-server
  namespace: scp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scp-server
  template:
    metadata:
      labels:
        app: scp-server
    spec:
      containers:
      - name: scp-server
        image: docker.io/xsylla/scp-server:latest
        command: ["/bin/bash", "-c"]
        args:
          - |
            steamcmd +force_install_dir /data/scp +login anonymous +app_update 996560 validate +quit
            curl -L -o "$mod/RemoteKeycard-LabAPI.dll" "https://github.com/Unbistrackted/RemoteKeycard/releases/latest/download/RemoteKeycard-LabAPI.dll"
            curl -L -o "$mod/ScpSwap.LabAPI.dll" "https://github.com/tayjay/ScpSwap-LabAPI/releases/latest/download/ScpSwap.LabAPI.dll"
            cd /data/scp
            exec ./LocalAdmin 7777
        env:
        - name: ACCEPT_SCPSL_EULA
          value: "TRUE"
        ports:
        - name: udp
          containerPort: 7777
          protocol: UDP
        #envFrom:
        #- configMapRef:
        #    name: scp-config
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: scp-data
          mountPath: /data
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  volumeClaimTemplates:
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: scp-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: local-path
      volumeMode: Filesystem
    status:
      phase: Pending
  serviceName: scp-server
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
